### PR TITLE
Fixed a bug in which gray images cause crash

### PR DESCRIPTION
**Pull request by CallShaul**
Now functions support 2 dimensions gray images, not only 3 dimensions color images.

### CODE REVIEW

**Comment by nekhtiari** [comment]
Nice, LGTM

**Comment by chrieke** [comment]
Hey @CallShaul, thank you for the PR and sorry about the longer inactivity. 

Wouldn't this also need to be applied on the second image?

**Comment by CallShaul** [comment]
@chrieke Hi, I'm not sure what you mean by "second image".

**Comment by nikooc2s** [comment]
> @chrieke Hi, I'm not sure what you mean by "second image".

I think he meant the predicted one. Your changes are only for original image.

**Comment by CallShaul** [comment]
@nikooc2s @chrieke No, there is no need to do anything else, using the `expand_dims` this way, adds a third dimension with size 1, so the argument in the for loop `org_img.shape[2]` will not fail, yet the number of iterations will be 1 in the case of a gray image. (image size will change from `[row, col]` to [`row, col, 1]`)

**Comment by nikooc2s** [comment]
> @nikooc2s @chrieke No, there is no need to do anything else, using the `expand_dims` this way, adds a third dimension with size 1, so the argument in the for loop `org_img.shape[2]` will not fail, yet the number of iterations will be 1 in the case of a gray image. (image size will change from `[row, col]` to [`row, col, 1]`)

Thanks for the explanation. Make sense to me. Unfortunately I can't merge your PR. We need to wait for @chrieke.

@chrieke is it possible I can have the possibility to merge PRs for this repo? Do i need to contact someone from UP42 to get the necessary permissions?

**Review by nekhtiari — APPROVED** [review]

**Pull request merged**
